
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 979776 bytes/channel
 *	Total Size: 1 * 979776 + 4 (header) = 979820 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\shais\OneDrive\Documents\2261\M03_TahirahAhmad - Copy\gameSong.wav
 *	Time-stamp: Thu Apr 12 20:45:24 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 979776

extern const unsigned char gameSong[979776];

#endif /* __GAMESONGH__ */
