
/**************************************************************
 *	
 *	Lorn, 8 bit, 11025Hz,
 *	1 channel, 1531584 bytes/channel
 *	Total Size: 1 * 1531584 + 4 (header) = 1531628 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\shais\OneDrive\Documents\2261\M03_TahirahAhmad - Copy\Lorn.wav
 *	Time-stamp: Thu Apr 12 20:04:38 2018
 *	
 **************************************************************/

#ifndef __LORNH__
#define __LORNH__

#define LORNFREQ 11025
#define LORNLEN 1531584

extern const unsigned char Lorn[1531584];

#endif /* __LORNH__ */
