
/**************************************************************
 *	
 *	shoot, 8 bit, 11025Hz,
 *	1 channel, 23040 bytes/channel
 *	Total Size: 1 * 23040 + 4 (header) = 23084 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\shais\OneDrive\Documents\2261\M03_TahirahAhmad - Copy\shoot.wav
 *	Time-stamp: Thu Apr 12 20:53:05 2018
 *	
 **************************************************************/

#ifndef __SHOOTH__
#define __SHOOTH__

#define SHOOTFREQ 11025
#define SHOOTLEN 23040

extern const unsigned char shoot[23040];

#endif /* __SHOOTH__ */
